### ISSUE TITLE
Issue with Denver's win total and Washington's games played

### ISSUE THREAD

**Issue by samir-hub** [mcbarlowe/seventhmanapi#1]
1. In the /teams endpoint, Denver's wins are consistently one less than the real wins. 
2. Also, as of 12/19, Washington has played 26 games but the API has "gp" at 25.

**Comment by mcbarlowe** [comment]
Just saw this will look into it could be an issue with the api or I haven't ran my scripts for whatever day. Also for future reference can you post the whole api url that you are having issues with so i can debug it easier.

**Comment by mcbarlowe** [comment]
https://stats.theseventhman.net/stats/api/v1/teams/ is now returning proper stats for GP and Wins at least for the DEN, WAS, and OKC which i checked. My scripts have to run locally because the NBA api blacklists AWS servers which i haven't found a way around. Please continue raising issues if you see something wrong I'm watching the repo now so I should be more proactive in fixing these in the future. ALso other stats are still processing and probably won't be finished until later this morning in terms or RAPM and advanced stats
